BaseURL: "http://leimar.nu"
languageCode: "sv-se"
title: ""
tagline: ""
params:
  onlyLogotype: true
  logotype: "start-640.jpg"
  footer: "copyright &copy; 2016 Eric Leimar"

MetaDataFormat: "toml"
blackfriday:
  extensions:
    - hardLineBreak
